### PR TITLE
Medical and Loadout Update

### PR DESCRIPTION
**Pull request by TheOtherTaylor**
-Add Ace Pointing
-Upgrade damage threshold to 1.2 to stopgap basic medical bug
-Update Blufor Loadouts (Lighter, Less Bloat)
-Update Opfor Loadouts (no more AGM)
-Update Squads to have 1 Heavy Weapons Team
-Load weapons first on loadouts or you get missing mag issues.

### CODE REVIEW

**Comment by TheOtherTaylor** [comment]
This took me a while to figure out how to do, but I think I did it right.

**Comment by astruyk** [comment]
Did you actually test the gear assignment changes? I didn't think using 'this' worked in those scripts. It either needs to be switched to 'player' or the assignGear function needs to pass the player as the argument so that its assigned to the 'this' variable.

**Comment by TheOtherTaylor** [comment]
I'll check it again right now I thought it was all working.

**Comment by TheOtherTaylor** [comment]
Fixed

**Pull request merged**
